export function buildReportHtml(mine = {}, result = {}) {
  const { answers = {}, proofs = {}, score, totalPoints, percentage, moduleScores = {} } = result;
  const date = new Date().toLocaleString();

  const pct = (percentage ?? (totalPoints ? ((Number(score) / Number(totalPoints)) * 100).toFixed(2) : "")) ?? "";
  const star = (p => {
    const n = Number(p);
    if (Number.isNaN(n)) return "N/A";
    if (n >= 90) return "★★★★★";
    if (n >= 75) return "★★★★";
    if (n >= 60) return "★★★";
    if (n >= 45) return "★★";
    return "★";
  })(pct);

  const escapeHtml = (s) => String(s ?? "").replace(/[&<>"']/g, c => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;" }[c]));

  const mineRows = Object.entries(mine)
    .filter(([k]) => k !== "scores" && k !== "proofs" && k !== "lastResult")
    .map(([k, v]) => `<tr><th>${escapeHtml(k)}</th><td>${escapeHtml(String(v))}</td></tr>`).join("") ||
    `<tr><td colspan="2">No mine details</td></tr>`;

  const moduleRows = Object.entries(moduleScores || {})
    .map(([k, v]) => `<tr><th>${escapeHtml(k)}</th><td>${escapeHtml(String(v))}</td></tr>`).join("") ||
    `<tr><td colspan="2">No module scores</td></tr>`;

  const answerRows = Object.entries(answers || {})
    .map(([k, v]) => `<tr><th>${escapeHtml(k)}</th><td>${escapeHtml(String(v))}</td></tr>`).join("") ||
    `<tr><td colspan="2">No answers</td></tr>`;

  const proofRows = Object.entries(proofs || {})
    .map(([k, f]) => {
      const name = escapeHtml(f?.name || "");
      if (f?.dataUrl && /^data:image/i.test(f.dataUrl)) {
        return `<tr><th>${escapeHtml(k)}</th><td>${name}<br/><img src="${f.dataUrl}" style="max-width:420px;height:auto;border:1px solid #ddd;margin-top:6px"/></td></tr>`;
      }
      if (f?.dataUrl) {
        // non-image dataURL — show filename and link for browsers that support blob URLs
        return `<tr><th>${escapeHtml(k)}</th><td>${name} (attached)</td></tr>`;
      }
      return `<tr><th>${escapeHtml(k)}</th><td>${name || "No file"}</td></tr>`;
    }).join("") || `<tr><td colspan="2">No proofs uploaded</td></tr>`;

  // Use /logo.png as app logo (served from public/)
  const logoHtml = `<img src="/logo.png" alt="Logo" style="max-height:84px;display:block;margin:0 0 12px 0" />`;

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Star Rating - ${escapeHtml(mine.name || "Report")}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <style>
    body{font-family:Arial,Helvetica,sans-serif;padding:18px;color:#222;background:#fff}
    .wrap{max-width:820px;margin:0 auto}
    h1{font-size:20px;margin:6px 0}
    .meta{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:12px}
    .badge{padding:6px 10px;background:#f8f8f8;border-radius:6px}
    table{width:100%;border-collapse:collapse;margin-bottom:14px}
    th,td{border:1px solid #e8e8e8;padding:8px;text-align:left;vertical-align:top}
    th{background:#fafafa;width:260px}
    img{max-width:100%;height:auto}
    .section{margin-bottom:18px}
    .small{font-size:0.9rem;color:#555}
  </style>
</head>
<body>
  <div class="wrap">
    ${logoHtml}
    <h1>Star Rating Report</h1>
    <div class="meta">
      <div class="badge"><strong>Mine:</strong> ${escapeHtml(mine.name || "")}</div>
      <div class="badge"><strong>Date:</strong> ${escapeHtml(date)}</div>
      <div class="badge"><strong>Score:</strong> ${escapeHtml(String(score ?? ""))} / ${escapeHtml(String(totalPoints ?? ""))}</div>
      <div class="badge"><strong>Percentage:</strong> ${escapeHtml(String(pct))}${pct !== "" ? "%" : ""}</div>
      <div class="badge"><strong>Star:</strong> ${escapeHtml(star)}</div>
    </div>

    <div class="section">
      <h2>Mine Details</h2>
      <table>${mineRows}</table>
    </div>

    <div class="section">
      <h2>Module Scores</h2>
      <table>${moduleRows}</table>
    </div>

    <div class="section">
      <h2>Answers</h2>
      <table>${answerRows}</table>
    </div>

    <div class="section">
      <h2>Proofs</h2>
      <table>${proofRows}</table>
    </div>

    <div class="small">Generated by Mine Star Rating App</div>
  </div>
</body>
</html>`;
}

export default buildReportHtml;